<?php
/**
 * EU AI Act transparency disclosure template.
 * Variables: $type (string), $provider (string), $content (string).
 */
if ( ! defined( 'ABSPATH' ) ) exit;

$labels = [
    'generated'       => __( 'This content was generated by AI', 'consentforge' ),
    'assisted'        => __( 'This content was created with AI assistance', 'consentforge' ),
    'chatbot'         => __( 'This service uses an AI-powered chat assistant', 'consentforge' ),
    'synthetic_media' => __( 'This media is synthetically generated', 'consentforge' ),
];

$label     = esc_html( $labels[ $type ?? 'generated' ] ?? $labels['generated'] );
$by        = $provider ? ' ' . sprintf( /* translators: %s: AI provider name */ esc_html__( 'by %s', 'consentforge' ), esc_html( $provider ) ) : '';
?>
<div class="cf-ai-disclosure" role="note" aria-label="<?php esc_attr_e( 'EU AI Act Disclosure', 'consentforge' ); ?>" style="display:flex;align-items:flex-start;gap:8px;padding:10px 14px;background:#fffbeb;border:1px solid #fcd34d;border-radius:6px;font-size:12px;color:#92400e;margin:12px 0">
    <span aria-hidden="true" style="font-size:14px">🤖</span>
    <div>
        <strong><?php esc_html_e( 'EU AI Act Disclosure:', 'consentforge' ); ?></strong>
        <?php echo $label . $by; // phpcs:ignore WordPress.Security.EscapeOutput ?>
    </div>
</div>
<?php if ( $content ) : ?>
<?php echo wp_kses_post( $content ); ?>
<?php endif; ?>
